// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgnnpsdrzlymkmksahgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbm5wc2Ryemx5bWtta3NhaGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzkzMzEsImV4cCI6MjA3MDg1NTMzMX0.XC4I-KtKyX21jnXJQJfjS1HD50ifAw-WE0mvKObecjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});